#include <stdio.h>
/* Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms 
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do 
not exceed four million, find the sum of the even-valued terms.
*/

int main(){

	int temp;              // needed for fib iteration
	int ceiling = 4000000; // calculate fib(n) up to ceiling
	int total = 0;         // running total of even terms
	int a = 1, b = 2;      // start with 1 and 2, as specified

	while (a < ceiling){

		temp = b;
		b = a + b;
		a = temp;

		if (a % 2 == 0){   // if fib term is even, add to total
			total += a;
		}
	}

	printf("%d\n\n", total);

	return 1;

}